"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0!-3+u*=$fz9zx(qujau83l+!l+ftwl-xw4vm422^uv&-g2#7e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'host.docker.internal']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'agent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# LangGraph / LLM (OpenRouter)
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY')
OPENROUTER_BASE_URL = os.environ.get('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1')
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'anthropic/claude-sonnet-4-6')
LANGGRAPH_DB_PATH = str(BASE_DIR / 'langgraph_state.sqlite')

# Evolution API (WhatsApp)
EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', 'http://localhost:8080')
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', '')
EVOLUTION_INSTANCE = os.environ.get('EVOLUTION_INSTANCE', 'Local')
# "digitando..." (presence composing) dura len(texto) * N ms antes de cada envio.
# ~30ms/char ≈ digitação humana e fica visível mesmo em mensagens curtas (0 desliga).
EVOLUTION_TYPING_MS_PER_CHAR = int(os.environ.get('EVOLUTION_TYPING_MS_PER_CHAR', '30'))
# Número de WhatsApp que recebe o aviso quando um lead pede atendimento humano.
# Vazio = handoff só registrado no admin (Lead.handoff_requested), sem aviso.
HANDOFF_NOTIFY_NUMBER = os.environ.get('HANDOFF_NOTIFY_NUMBER', '')
# Token compartilhado do webhook da Evolution (configure a URL do webhook com
# ?token=<valor>). Vazio = aceita qualquer chamada (apenas para dev local).
EVOLUTION_WEBHOOK_TOKEN = os.environ.get('EVOLUTION_WEBHOOK_TOKEN', '')
# Comma-separated allowlist of WhatsApp numbers the bot may reply to.
# Leave empty to reply to anyone who sends a 1:1 message.
EVOLUTION_ALLOWED_NUMBERS = [
    n.strip()
    for n in os.environ.get('EVOLUTION_ALLOWED_NUMBERS', '').split(',')
    if n.strip()
]

# Debounce (agrupa mensagens do WhatsApp recebidas em rajada num só turno).
# Reusa o Redis do stack da Evolution, isolado no DB index 1 (Evolution usa o 0).
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/1')
DEBOUNCE_SECONDS = float(os.environ.get('DEBOUNCE_SECONDS', '8'))
